//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicaMedica.Model
{
    using System;

    public partial class AgendaExame
    {
        public int IdAgendaExame { get; set; }
        public int IdentificacaoPaciente { get; set; }
        public int IdExame { get; set; }
        public int IdConsultorio { get; set; }
        public DateTime DataHoraInicio { get; set; }
        public DateTime DataHoraFim { get; set; }
        public bool Comparecimento { get; set; }
        public string Anotacoes { get; set; }
    
        public virtual Paciente Paciente { get; set; }
        public virtual Exame Exame { get; set; }
        public virtual Consultorio Consultorio { get; set; }
    }
}
