//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicaMedica.Model
{
    using System;
    using System.ComponentModel.DataAnnotations;

    public partial class Consulta
    {
        public int IdConsulta { get; set; }
        public int IdentificacaoPaciente { get; set; }
        public int IdentificacaoMedico { get; set; }
        public int IdConsultorio { get; set; }
        [Required(ErrorMessage = "O campo 'Horário (Inicial)' é obrigatório!", AllowEmptyStrings = false)]
        public DateTime DataHoraInicio { get; set; }
        [Required(ErrorMessage = "O campo 'Horário (Final)' é obrigatório!", AllowEmptyStrings = false)]
        public DateTime DataHoraFim { get; set; }
        [Required(ErrorMessage = "O campo 'Comparecimento' é obrigatório!")]
        public bool Comparecimento { get; set; }
        public string Anotacoes { get; set; }
    
        public virtual Paciente Paciente { get; set; }
        public virtual Medico Medico { get; set; }
        public virtual Consultorio Consultorio { get; set; }
    }
}
