//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicaMedica.Model
{
    using System;
    
    public enum ProductType : int
    {
        Medicamento = 1,
        MaterialHospitalar = 2,
        ProdutoLimpeza = 3,
        Outro = 4
    }
}
