//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicaMedica.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Telefone
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Telefone()
        {
            this.DDI = "55";
        }
    
        public string DDI { get; set; }
        public string DDD { get; set; }
        public string Numero { get; set; }
        public Nullable<int> IdentificacaoPessoa { get; set; }
        public Nullable<int> IdConsultorio { get; set; }
        public PhoneType Tipo { get; set; }
    
        public virtual Usuario Pessoa { get; set; }
        public virtual Consultorio Consultorio { get; set; }
    }
}
